project:
  type: website
  output-dir: docs

website:
  title: "MSc Economics Starter Kit"

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home

      - section: "Mathematics & Statistics"
        href: maths_stats.qmd
        contents:
          - href: maths-quiz.qmd
            text: Maths Quiz

      - section: "Macroeconomics"
        href: macro.qmd
        contents:
          - href: macro-quiz.qmd
            text: Macro Quiz

      - section: "Microeconomics"
        href: micro.qmd
        contents:
          - href: micro-quiz.qmd
            text: Micro Quiz

      - section: "Econometrics"
        href: metrix.qmd
        contents:
          - href: stats-quiz.qmd
            text: Econometrics Quiz

format:
  html:
    theme: cosmo
    dark: darkly
    toc: true
    toc-depth: 3
    number-sections: false
    fig-align: center
    embed-resources: true
    smooth-scroll: true

bibliography: starter_kit.bib

execute:
  freeze: auto
    
